apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: radio
  name: radio
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: radio
  type: LoadBalancer
status:
  loadBalancer: {}